#!/usr/bin/env python3
"""Auto-fix safe markdown format issues in docs/.

Phase 1-4 (from the report):
  1. empty files           -> SKIP (we list them and let user decide)
  2. useless-escape        -> strip \ between word chars
  3. triple-blank          -> collapse 3+ blank lines to 2
  4. fence-no-lang         -> ``` -> ```text

Run on /Users/growduduan/code/blog/docs only (not source/_posts/, which is
generated by sync-hexo.py from docs/).
"""
import os, re, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'docs')

# 1) collect empty files (don't delete automatically)
empty_files = []
fixed_files = []
unchanged_files = []

USELESS_RE = re.compile(r'(?<=[A-Za-z0-9])\\(?=[A-Za-z0-9])')   # word\word
TRIPLE_RE  = re.compile(r'\n{3,}')                              # 3+ newlines
FENCE_RE   = re.compile(r'^```\s*$', re.MULTILINE)              # bare ```

# Per-file counters (only changes in this run)
counters = {'useless-escape': 0, 'triple-blank': 0, 'fence-no-lang': 0}

for dp, dn, fn in os.walk(ROOT):
    for fname in fn:
        if not fname.endswith('.md'):
            continue
        path = os.path.join(dp, fname)
        if os.path.getsize(path) == 0:
            empty_files.append(path)
            continue
        with open(path, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read()
        original = content

        # useless-escape
        n = len(USELESS_RE.findall(content))
        content = USELESS_RE.sub('', content)
        counters['useless-escape'] += n

        # triple-blank
        m = TRIPLE_RE.findall(content)
        content = TRIPLE_RE.sub('\n\n', content)
        counters['triple-blank'] += len(m)

        # fence-no-lang
        fence_lines = FENCE_RE.findall(content)
        content = FENCE_RE.sub('```text', content)
        counters['fence-no-lang'] += len(fence_lines)

        if content != original:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(content)
            fixed_files.append(path)
        else:
            unchanged_files.append(path)

print('=== SUMMARY ===')
print(f'Fixed files:        {len(fixed_files)}')
print(f'Unchanged files:    {len(unchanged_files)}')
print(f'Empty files (kept): {len(empty_files)}')
print()
print('=== Per-issue counts (deltas applied) ===')
for k, v in counters.items():
    print(f'  {k:20s} {v:5d}')
print()
print('=== Empty files (NOT touched — please review) ===')
for p in sorted(empty_files):
    print(f'  {os.path.relpath(p, ROOT)}')
