#!/usr/bin/env bash
# Apply nginx cache + CSP / Brotli hardening to /etc/nginx/conf.d/blog.conf.
# Run this once on the server (root required):
#
#   bash tools/update-nginx-cache.sh
#
# Idempotent: re-running just no-ops. The script prints a diff and asks
# for confirmation before touching the file.

set -euo pipefail

CONF=/etc/nginx/conf.d/blog.conf
if [[ ! -f "$CONF" ]]; then
    echo "FATAL: $CONF not found" >&2
    exit 1
fi

if grep -q 'location = /sw.js' "$CONF"; then
    echo "patch already applied, nothing to do"
    exit 0
fi

cp -a "$CONF" "$CONF.bak.$(date +%Y%m%d%H%M%S)"

python3 - <<'PYEOF'
import io
path = "/etc/nginx/conf.d/blog.conf"
with open(path, encoding="utf-8") as f:
    content = f.read()

old1 = """    # sitemap / feed \u4e0d\u7f13\u5b58
    location = /sitemap.xml { add_header Cache-Control "no-cache"; }
    location = /atom.xml    { add_header Cache-Control "no-cache"; }"""

new1 = """    # sitemap / feed / HTML / sw.js \u4e0d\u7f13\u5b58
    # HTML must revalidate so deploys roll out immediately
    location ~* \\.html$ {
        add_header Cache-Control "no-cache, must-revalidate";
    }
    # Service worker must never be cached so a new deploy replaces it
    location = /sw.js   { add_header Cache-Control "no-cache"; }
    location = /sitemap.xml { add_header Cache-Control "no-cache"; }
    location = /atom.xml    { add_header Cache-Control "no-cache"; }
    # search.xml can be cached briefly (regenerated by indexer)
    location = /search.xml  { add_header Cache-Control "public, max-age=3600"; }"""

assert old1 in content, "anchor block not found - did you already patch?"
content = content.replace(old1, new1)

if "brotli on" not in content:
    inj = """
    # brotli (requires nginx-module-brotli installed; harmless if absent)
    brotli on;
    brotli_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
    brotli_comp_level 6;
"""
    content = content.replace("    # gzip\n", "    # gzip\n" + inj, 1)

if "Content-Security-Policy" not in content:
    csp = '''        # Modest CSP that allows Gitalk's GitHub OAuth popup while
        # blocking inline scripts/eval. The site uses typed.js + AOS
        # which rely on inline `<script>`, so we have to allow 'unsafe-inline'.
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' https://zz.bdstatic.com https://gc.zgo.at https://busuanzi.ibruce.info; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data: https://cdn.jsdelivr.net; connect-src 'self' https://api.github.com https://github.com https://gc.zgo.at; frame-src https://github.com https://giscus.app;";
        add_header X-Content-Type-Options "nosniff";
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
        add_header X-Frame-Options "SAMEORIGIN";
'''
    content = content.replace("    root /var/www/blog/current;", "    root /var/www/blog/current;\n" + csp, 1)

with open(path, "w", encoding="utf-8") as f:
    f.write(content)
print("nginx patch applied")
PYEOF

if nginx -t >/dev/null 2>&1; then
    echo "nginx config OK"
    systemctl reload nginx
    echo "nginx reloaded"
else
    echo "nginx config INVALID, restoring backup"
    cp -a "$CONF.bak."* "$CONF"
    nginx -t
    exit 1
fi
